version: '2'
services:
  apache:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    links:
      - redis
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
    - '8080:80'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
  redis:
    image: redis